### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by pbrissaud** [rueian/gke-hubble-export#2]
Hi,

First, thanks for your project ! It works very well 

I was asking if it was possible to enable Prometheus metrics of Hubble ? 

Thanks

**Comment by rueian** [comment]
Hi @pbrissaud,

Yes, You can enable Hubble metrics even without this project!

You need to:
1. `kubectl edit configmap -n kube-system cilium-config`
2. add these two configs: 
`hubble-metrics: "flow drop icmp port-distribution tcp"`
 `hubble-metrics-server: ":9091"`
3. restart all anet daemonset, you can use `kubectl rollout restart` to do that.

Please note that L7 Hubble metrics such as http and dns requires Cilium L7 Policy enabled, but GKE Dataplane V2 doesn't support it.

**Comment by pbrissaud** [comment]
Thanks it works well !

I added the port 9091 to the daemonset :
```
ports:
- containerPort: 9091
   hostPort: 9091
   name: hubble-metrics
   protocol: TCP
```

Then deploy a PodMonitor :
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium
  namespace: kube-system
  labels:
    app: cilium
spec:
  selector:
    matchLabels:
      k8s-app: cilium
  podMetricsEndpoints:
    - port: advdpmetrics
    - port: hubble-metrics
```
